/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * SourceForm.java
 *
 * Created on 05.apr.2010, 16:12:04
 */
package robotapplet;

import org.hibu.atek.tordf.SourceProvider;
import java.util.ArrayList;
import org.hibu.atek.tordf.io.SaveHandler;

/**
 *
 * @author Tord
 */
public class SourceForm extends javax.swing.JFrame {

    protected SourceProvider sourceProvider;

    /**
     * Get the value of sourceProvider
     *
     * @return the value of sourceProvider
     */
    public SourceProvider getSourceProvider() {
        return sourceProvider;
    }

    /**
     * Set the value of sourceProvider
     *
     * @param sourceProvider new value of sourceProvider
     */
    public void setSourceProvider(SourceProvider sourceProvider) {
        this.sourceProvider = sourceProvider;
        jEditorPane1.setText(sourceProvider.GetSource());
    }

    /** Creates new form SourceForm */
    public SourceForm() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jEditorPane1 = new javax.swing.JEditorPane();
        closeButton = new javax.swing.JButton();
        SaveButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jScrollPane1.setViewportView(jEditorPane1);

        closeButton.setText("Close");
        closeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeButtonActionPerformed(evt);
            }
        });

        SaveButton.setText("Save");
        SaveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(268, Short.MAX_VALUE)
                .addComponent(SaveButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(closeButton)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(closeButton)
                    .addComponent(SaveButton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    protected ArrayList<SaveHandler> saveHandlers = new ArrayList<SaveHandler>();

    /**
     * Get the value of saveHandler
     *
     * @return the value of saveHandler
     */
    public ArrayList<SaveHandler> getSaveHandler() {
        return saveHandlers;
    }

    /**
     * Set the value of saveHandler
     *
     * @param saveHandler new value of saveHandler
     */
    public void addSaveHandler(SaveHandler saveHandler) {
        this.saveHandlers.add(saveHandler);
    }

    private void SaveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveButtonActionPerformed

        for (SaveHandler sh : saveHandlers) {
            sh.Save(jEditorPane1.getText());
        }
    }//GEN-LAST:event_SaveButtonActionPerformed

    private void closeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeButtonActionPerformed
        this.dispose();
    }//GEN-LAST:event_closeButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new SourceForm().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton SaveButton;
    private javax.swing.JButton closeButton;
    private javax.swing.JEditorPane jEditorPane1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
